apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: togglemaster-targeting
  newName: 174935208848.dkr.ecr.us-east-1.amazonaws.com/togglemaster-targeting
  newTag: v1.0.0-f45735d
