apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-db-init-sql
  namespace: togglemaster
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS targeting_rules (
        id SERIAL PRIMARY KEY,
        flag_name VARCHAR(100) UNIQUE NOT NULL,
        is_enabled BOOLEAN NOT NULL DEFAULT true,
        rules JSONB NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
    CREATE OR REPLACE FUNCTION trigger_set_timestamp()
    RETURNS TRIGGER AS $$
    BEGIN
      NEW.updated_at = NOW();
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    DROP TRIGGER IF EXISTS set_timestamp ON targeting_rules;
    CREATE TRIGGER set_timestamp BEFORE UPDATE ON targeting_rules FOR EACH ROW EXECUTE PROCEDURE trigger_set_timestamp();
---
apiVersion: batch/v1
kind: Job
metadata:
  name: targeting-db-setup
  namespace: togglemaster
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:15-alpine
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: targeting-db-secret
              key: DATABASE_URL
        command: ["/bin/sh", "-c", "psql $DATABASE_URL -f /scripts/init.sql"]
        volumeMounts:
        - name: sql-volume
          mountPath: /scripts
      volumes:
      - name: sql-volume
        configMap:
          name: targeting-db-init-sql
      restartPolicy: OnFailure