apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
      - name: analytics-service
        image: togglemaster-analytics # O Kustomize vai trocar isso pelo endereço do ECR
        ports:
        - containerPort: 8005

        envFrom:
        - configMapRef:
            name: analytics-config
        - secretRef:
            name: aws-credentials

        # ---> VARIÁVEIS DO OPENTELEMETRY <---
        env:
        - name: OTEL_SERVICE_NAME
          value: "analytics-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector.observabilidade.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        # 1. Força o uso de gRPC (compatível com a porta 4317)
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        # 2. Crucial para o Datadog agrupar o mapa: env e version
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=prod,service.version=1.0.0"
        - name: OTEL_PROPAGATORS 
          value: "tracecontext,baggage"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 20
          periodSeconds: 15