apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 277688492624.dkr.ecr.us-east-1.amazonaws.com/togglemaster-flag
    newName: 277688492624.dkr.ecr.us-east-1.amazonaws.com/togglemaster-flag
    newTag: latest
